site_name: Crypto
site_url: https://github.com/yogk/crypto.git
site_description: Project documentation with Markdown.
site_author: Yogesh Kulkarni
nav:
  - Home: index.md
  - Cryptography_Basics: cryptography_basics.md
theme: readthedocs
